# Copyright 2014 The Moore Collective, LLC, All Rights Reserved

CLASS = 'profile'
ID = CLASS+'id'
U_ID = 'u_id'
U_SN = 'u_sn'
SNAME_INP = 'snametxtid'
SNAME_OPT = 'snameoptid'
NAME_INP = 'nametxtid'
NAME_OPT = 'nameoptid'
EMAIL_INP = 'emailtxtid'
EMAIL_OPT = 'emailoptid'
COUNTRY_INP = 'countrytxtid'
COUNTRY_OPT = 'countryoptid'
PHONE_INP = 'phonetxtid'
PHONE_OPT = 'phoneoptid'
PIC_OPT = 'profilepicoptid'
MOOD_CUR_OPT = 'moodcuroptid'
MOOD_LIM_OPT = 'moodlimoptid'
MOOD_ALL_OPT = 'moodalloptid'
